name: Coverage Badge
description: Badges for test results and code coverage

# Required for publishing to the marketplace:
# Improve your Action by adding labels for icon and color.
branding:
  icon: check-circle
  color: green

inputs:
  version:
    description: Version string will be appended to the badge filename
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Get coverage
      id: coverage
      shell: bash
      run: |
        COVERAGE=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...[`lines`,`functions`,`branches`].map(k=>t[k].pct))')
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Get color
      id: color
      shell: bash
      run: |
        COLOR=$(node -p '+${{ steps.coverage.outputs.coverage }} >= 95 ? `green` : +${{ steps.coverage.outputs.coverage }} >= 50 ? `orange` : `red`')
        echo "color=$COLOR" >> $GITHUB_OUTPUT

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Generate badge
      id: badge
      uses: emibcn/badge-action@v2.0.3
      with:
        label: 'coverage'
        color: ${{ steps.color.outputs.color }}
        status: "${{ format('{0}%', steps.coverage.outputs.coverage) }}"
        path: "badges/coverage${{ inputs.version && format('-{0}', inputs.version) }}.svg"

    - name: Deploy Badge to gh-pages
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Update badge [skip ci]'
        branch: gh-pages
        skip_fetch: true
        skip_checkout: true

    # Without this, will get Error:
    # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/coverage-badge-action/coverage-badge-action/action.yml'.
    # Did you forget to run actions/checkout before running your local action?
    - name: Checkout Back
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
